title: Larry Velazquez # your name (or website title) here
logo: "/images/prototype Mark2.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A Student attending Columbia College Chicago 
  <br><br>
  Looking to expand my knowledge in any way that I can! 
  <br><br> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
